[book]
authors = ["Dhruv Sangamwar", "Avni Bafna", "Priyal Patel", "Aryaman Bhatia", "Grace Lim", "Sofia Fischel", "Manik Sethi"]
language = "en"
multilingual = false
src = "src"
title = "Neurotech@Davis Wiki"
